# Dependencias (tiene todo los modulos de node)
FROM node:22-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

# Builder - Construye la aplicación
FROM node:22-alpine3.19 as build

WORKDIR /usr/src/app

# Copiar de deps. los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .

# RUN npm run test
RUN npm run build

#se puede hacer una limpieza de todos los modulos de node que no necesito, solo dejar los de producción (ayuda a reducir el peso)
RUN npm prune --production && npm cache clean --force
# RUN npm ci -f --omit=dev && npm cache clean --force



# Crear la imagen final de Docker
FROM node:22-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST  (solo javascript)
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]
